In [4]:
# using numpy
import numpy as np

n1 = np.array([1, 2, 3])
n2 = np.array([[1, 2, 3],
               [4, 5, 6]])
n3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(n1.shape, n2.shape, n3.shape)


(3,) (2, 3) (2, 2, 2)


In [2]:
#using pytorch
import torch

t1 = torch.tensor([1, 2, 3])

t2 = torch.tensor([[1, 2, 3],
                   [4, 5, 6]])

t3 = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(t1.shape)
print(t2.shape)
print(t3.shape)


torch.Size([3])
torch.Size([2, 3])
torch.Size([2, 2, 2])


In [ ]:
# basic operations using numpy
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition ",a + b)
print("Subtraction ",a - b)
print("Multiplication ",a * b)
print("Division ",a / b)

print("Dot Product ",np.dot(a, b))

Addition  [5 7 9]
Subtraction  [-3 -3 -3]
Multiplication  [ 4 10 18]
Division  [0.25 0.4  0.5 ]
Dot Product  32
Matrix Multiplication  32


In [ ]:
# basic operations using pytorch
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print("Addition ",a + b)
print("Subtraction ",a - b)
print("Multiplication ",a * b)
print("Division ",a / b)

print("Dot Product",torch.dot(a, b))


Addition  tensor([5, 7, 9])
Subtraction  tensor([-3, -3, -3])
Multiplication  tensor([ 4, 10, 18])
Division  tensor([0.2500, 0.4000, 0.5000])
Dot Product tensor(32)


In [ ]:
#matrix multiplication using pytorch
A = torch.tensor([[1, 2],
                  [3, 4]])
B = torch.tensor([[5, 6],
                  [7, 8]])

print(torch.matmul(A, B))

tensor([[19, 22],
        [43, 50]])


In [ ]:
#matrix multiplication using numpy
A @ B

tensor([[19, 22],
        [43, 50]])

In [ ]:
#slicing
print("using pytorch")
t = torch.tensor([[10, 20, 30],
                  [40, 50, 60]])

print(t[0])
print(t[1, 2])
print(t[:, 1])
print("\n")
print("using numpy")
t = np.array([[10, 20, 30],
              [40, 50, 60]])

print(t[0])
print(t[1, 2])
print(t[:, 1])

using pytorch
tensor([10, 20, 30])
tensor(60)
tensor([20, 50])


using numpy
[10 20 30]
60
[20 50]


In [ ]:
#boolean masking
print("using pytorch")
t = torch.tensor([1, 5, 8, 2, 9])
mask = t > 5
print(mask)
print(t[mask])

print("\nusing numpy")
t = np.array([1, 5, 8, 2, 9])
t[t > 5]

using pytorch
tensor([False, False,  True, False,  True])
tensor([8, 9])

using numpy


array([8, 9])

In [ ]:
#extracting subtensors
t = torch.arange(16).reshape(4, 4)

sub = t[1:3, 1:3]
print(sub)


tensor([[ 5,  6],
        [ 9, 10]])


In [3]:
# view in tensors
x = torch.arange(6)
y = x.view(2, 3)
print(y)


tensor([[0, 1, 2],
        [3, 4, 5]])


In [5]:
# reshape in numpy
x.reshape(3, 2)

# reshape in torch
z = x.reshape(3, 2)

In [6]:
# squeeze in torch
x = torch.tensor([[1, 2, 3]])

print(x.shape)
print(x.squeeze().shape)

torch.Size([1, 3])
torch.Size([3])


In [7]:
# unsqueeze in torch
x = torch.tensor([1, 2, 3])

print(x.shape)
print(x.unsqueeze(0))
print(x.unsqueeze(1))


torch.Size([3])
tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3]])


In [11]:
#broadcasting failures
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

b = torch.tensor([10, 20, 30])

print(a + b)


tensor([[11, 22, 33],
        [14, 25, 36]])


In [8]:
# inplace operations
x = torch.tensor([1, 2, 3])
y = x + 1

print(x)


tensor([1, 2, 3])


In [10]:
# outplace operations
x = torch.tensor([1, 2, 3])
x += 1

print(x)

tensor([2, 3, 4])
